title:              Daphne Miedema
email:              daphne@altmails.com
description:        Database Interaction and Education Research
author:             Daphne Miedema
#baseurl:            "/page"
#url:                http://giraphne.github.io
theme:              jekyll-theme-clean-blog

# Social Profiles
github_username:    Giraphne
linkedin_username:  daphnemiedema
twitter_username:   DaphneMiedema

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-158532946-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site