title:              Daphne Miedema
email:              d.e.miedema@uva.nl
description:        Database Interaction and Education Research
author:             Daphne Miedema
#baseurl:            "/page"
#url:                http://giraphne.github.io
remote_theme:       StartBootstrap/startbootstrap-clean-blog-jekyll

# Social Profiles
github_username:    Giraphne
linkedin_username:  daphnemiedema
twitter_username:   DaphneMiedema

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-GMP16HB5SH # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site